# Generated by Django 4.2.5 on 2023-09-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=124)),
            ],
            options={
                'verbose_name_plural': 'Подтип блюда',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=124)),
            ],
            options={
                'verbose_name_plural': 'Тип блюда',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_image', models.ImageField(upload_to='Food_image/', verbose_name='Изображение блюда')),
                ('Food_name', models.CharField(max_length=64, verbose_name='Название блюда')),
                ('Food_price', models.IntegerField(verbose_name='Цена блюда')),
                ('Food_info', models.TextField(verbose_name='Описание блюда')),
                ('Food_subType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_subtype', to='Foods.subtypes', verbose_name='Подтип блюда')),
                ('Food_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_type', to='Foods.types', verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Блюда',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
