# Generated by Django 4.2.5 on 2023-09-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtypes',
            name='alpha_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_types', to='Foods.types', verbose_name='Тип блюда'),
            preserve_default=False,
        ),
    ]
