# Generated by Django 4.2.5 on 2023-09-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0005_remove_food_food_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'тип блюда', 'verbose_name_plural': ' Тип блюда'},
        ),
        migrations.RemoveField(
            model_name='food',
            name='Food_info',
        ),
    ]
