# Generated by Django 4.2.5 on 2023-09-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0006_alter_types_options_remove_food_food_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='types',
            field=models.CharField(max_length=124, verbose_name='категория'),
        ),
    ]
