# Generated by Django 4.2.5 on 2023-09-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0007_alter_types_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_type', to='Foods.types', verbose_name='cat'),
        ),
        migrations.AlterField(
            model_name='types',
            name='types',
            field=models.CharField(max_length=124, verbose_name='name'),
        ),
    ]
