# Generated by Django 4.2.5 on 2023-09-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0008_alter_food_food_type_alter_types_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_type', to='Foods.types', verbose_name='Тип блюда'),
        ),
        migrations.AlterField(
            model_name='types',
            name='types',
            field=models.CharField(max_length=124),
        ),
    ]
