# Generated by Django 4.2.5 on 2023-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foods', '0010_remove_food_food_type_food_types_delete_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_menu',
            field=models.CharField(choices=[('бар', 'бар'), ('кафе', 'кафе')], default=1, max_length=124, verbose_name='тип меню'),
            preserve_default=False,
        ),
    ]
